### ISSUE TITLE
How to refresh the access token obtained from api.auth.getAccessToken

### ISSUE THREAD

**Issue by 0xknon** [thedist/Twitch_API_v5#9]
In Twitch Doc, access token will expire so we need to refresh the access token by a refresh token. How to achieve this in this API?

**Comment by thedist** [comment]
Sorry about that oversight, when I released this module refreshing tokens wasn't needed as tokens didn't expire (and those of us who have an older client-id still don't have to deal with expiration at all, even on new tokens).

I've just updated the module to add the endpoint to refresh tokens, so download the latest version and you should be good :)
